name: Add & Commit
description: Add & commit files from a path directly from GitHub Actions

inputs:
  add:
    description: Arguments for the git add command
    required: false
    default: '.'
  author_name:
    description: The name of the user that will be displayed as the author of the commit
    required: false
  author_email:
    description: The email of the user that will be displayed as the author of the commit
    required: false
  branch:
    description: Name of the branch to use, if different from the one that triggered the workflow
    required: false
  cwd:
    description: The directory where your repository is located. You should use actions/checkout first to set it up
    required: false
    default: '.'
  default_author:
    description: How the action should fill missing author name or email.
    required: false
    default: 'github_actor'
  message:
    description: The message for the commit
    required: false
  pull_strategy:
    description: The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
    required: false
    default: '--no-rebase'
  push:
    description: Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (more info in the README)
    required: false
    default: 'true'
  remove:
    description: Arguments for the git rm command
    required: false
  signoff:
    description: Whether to use the --signoff option on git commit
    required: false
  tag:
    description: Arguments for the git tag command (the tag name always needs to be the first word not preceded by a hyphen)
    required: false
    
  # Input not required from the user
  github_token:
    description: The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
    required: false
    default: ${{ github.token }}

outputs:
  committed:
    description: Whether the action has created a commit.
  pushed:
    description: Whether the action has pushed to the remote.
  tagged:
    description: Whether the action has created a tag.

runs:
  using: node12
  main: lib/index.js

branding:
  icon: git-commit
  color: gray-dark
