name: 'Add & Commit'
description: 'Add & commit files from a path directly from GitHub Actions'

inputs:
  author_name:
    description: 'The name of the user that will be displayed as the author of the commit, defaults to author name of head commit'
    required: false
  author_email:
    description: 'The email of the user that will be displayed as the author of the commit, defaults to author email of head commit'
    required: false
  force:
    description: 'Whether to use the force option on git add, in order to bypass eventual gitignores'
    required: false
    default: false
  message:
    description: 'The message for the commit'
    required: true
    default: 'Commit from GitHub Actions'
  path:
    description: 'The path to stage files from'
    required: true
    default: '.'
  pattern:
    description: 'The pattern that mathces file names'
    required: false
    default: "*.*"
    
runs:
  using: 'docker'
  image: 'Dockerfile'

branding: 
  icon: 'git-commit'
  color: black