name: Add & Commit
description: Add & commit files from a path directly from GitHub Actions

inputs:
  add:
    description: Arguments for the git add command
    required: false
    default: "."
  author_name:
    description: The name of the user that will be displayed as the author of the commit
    required: false
  author_email:
    description: The email of the user that will be displayed as the author of the commit
    required: false
  cwd:
    description: The directory where your repository is located. You should use actions/checkout first to set it up
    required: false
    default: "."
  force:
    description: Whether to use the force option on git add, in order to bypass eventual gitignores
    required: false
    default: "false"
  message:
    description: The message for the commit
    required: false
    default: Commit from GitHub Actions
  ref:
    description: Name of the branch to use, if different from the one that triggered the workflow
    required: false
  remove:
    description: Arguments for the git rm command
    required: false
    default: ""

runs:
  using: node12
  main: lib/index.js

branding:
  icon: git-commit
  color: gray-dark
