import YAML from 'yamljs'
import fs from 'fs'

const actionManifest = YAML.load('action.yml'),
  inputs = Object.keys(actionManifest?.inputs || {})

fs.writeFileSync('src/inputs.ts', `
// WARNING: this file is auto-generated by scripts/inputs.ts (npm run inputs), any manual edit will be overwritten.

export type Input = ${inputs.map(s => `'${s}'`).join(' | ')}
`.trimLeft())
