name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Verify lib/ matches source
        id: verify-lib
        run: |
          if [ "$(git diff --ignore-space-at-eol --text -- lib/ | wc -l)" -gt "0" ]; then
            echo "Committed lib/ is out of sync with src/. Run npm ci && npm run build and commit lib/."
            git diff --ignore-space-at-eol --text -- lib/
            exit 1
          fi
      - if: ${{ failure() && steps.verify-lib.outcome == 'failure' }}
        name: Upload expected lib/
        uses: actions/upload-artifact@v7
        with:
          name: lib
          path: lib/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run lint
